server:
  port: 8081

# JasyptUtils
jasypt:
  encryptor:
    password: 7777777

spring:
  # DB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.219.153.31:3306/flow_job?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: brozen
    password: 159000
