server:
  port: 8081

# JasyptUtils
jasypt:
  encryptor:
    password: 7777777

spring:
  # DB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.219.153.31:3306/flow_job?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: brozen
    password: 159000
#    url: jdbc:mysql://127.0.0.1:3306/flow_job?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#    username: root
#    password: root

flowjob:
  tracker:
    name: leader
    cluster: leader=http://127.0.0.1:8081


