server:
  port: 8081

flowjob:
  worker:
    brokers:
      - http://localhost:8081
    tags:
      - a=b
      - c=d

spring:
  # DB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.219.153.31:3306/flow_job?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: brozen
    password: 159000
#    url: jdbc:mysql://127.0.0.1:3306/flow_job?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#    username: root
#    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true  # 日志中显示sql语句


