server:
  port: 8084
spring:
  application:
    name: job-worker

flowjob:
  worker:
    id: abc
    host: 127.0.0.1
    port: 8084
    brokers:
      - http://localhost:8080/broker
    tags:
      - a=b
      - c=d